#!/bin/ksh

# ni'o ko'a goi le proga co'e cu jai filiri'a lo nu fanva fi le glibau kei ni'i zo'e joi le su'u vo'a zmiku lo nu basti pe'a
#
# .i ku'i jitfa fa le du'u ko'a mapti lo ro co'e  .i troci zo'e naje lo nu ko'a mapti lo se me'oi .kibykaerni.

sed -e "s/\\* le ka ce'u mutce le ka ko'a goi ce'u xi re gleki le su'u ko'a nonlingeni je le su'u ko'a jimpe le du'u ko'a nonlingeni kei kei je le su'u le ka ce'u xi ci nonlingeni cu jinzi ko'a gi ga ce/* that (VARIK is extreme in being glad about that (VARIK is agender), that (VARIK understands that VARIK is agender), and that (being agender is inherent to VARIK)),/" |\
sed -e "s/\\* le ka ce'u gleki le su'u ri ckaji le ka ce'u xi re tonsi noi ku'i ke'a jinzi ga naje ce'u gi ri joi le xadni be ri gi ga ce/* that (VARIK is glad about that (VARIK is transgender) (which is not inherent to VARIK but is inherent to the combination of VARIK and the body of VARIK)),/" |\
sed -e "s/\\* le ka ce'u milxe ko'a goi le ka su'u lingeni kei tolpu'a ce'u xi re gi ga ce/* that (VARIK somewhat experiences gender dysphoria),/" |\
sed -e "s/\\* le ka ce'u cortu le pagbu be le stedu be ce'u gi ga ce/* that (VARIK experiences pain in the head of VARIK),/" |\
sed -e "s/\\* le ka ce'u milxe le ka ce'u xi re tatpi gi ga ce/* that (VARIK is somewhat tired),/" |\
sed -e "s/\\* le ka ce'u cizra sipna gi ga ce/* that (VARIK oddly sleeps),/" |\
sed -e "s/\\* le ka ce'u dukse le ka ce'u xi re sipna gi ga ce/* that (VARIK excessively sleeps),/" |\
sed -e "s/\\* le ka ce'u pinxe loi kafxu'i je milgra be li ji'i vo bi no gi ga ce/* that (VARIK consumes caffeine, and the milligramme-based amount approximately equals 480),/" |\
sed -e "s/\\* le ka ce'u zu'edji lo ka ce'u xi re badgau je sidju lo ro prenu noi mupli tu'a ke'a fa lo zukte be lo mabla ja tolvu'e kei poi ke'a ckaji le ka ce'u xi re to'e vlile je cu jai toljursa kei ni'i zo'e joi lo su'u ke'a mapti py ky goi le ka ro da poi ke'a prenu zo'u ce'u xi re prami da gi ga ce/* that (VARIK intends that (VARIK protects and assists all prenu (which are exemplified by prenu which enact stuff which is fucked or immoral)) (which is anti-violent, is gentle, and is in accordance with the property of loving all prenu)),/" |\
sed -e "s/\\* le ka ce'u banzuka py ky le ka ce'u xi re milxe ko'a goi le ka ce'u xi ci klaku gi ga ce/* that (VARIK is sufficient (for that VARIK _slightly_ cries) in the property of loving all prenu),/" |\
sed -e "s/\\* le ka ce'u milxe le ka ce'u xi re djica lo nu ri klaku gi ga ce/ that (VARIK somewhat desires that VARIK cries),/" |\
sed -e "s/\\* le ka le ro bangu be ce'u cu to'e banzuka fi lo ka ce'u xi re bangu fi lo velcki be le nu ce'u xi pa re'enje djica py ky sy gi ga ce/* that (all languages which are used by VARIK are insufficient for communicating the extent of that VARIK spiritually desires $PKS$),/" |\
sed -e "s/\\* le ka ce'u ci'au .oi re'e ga je.../* that (VARIK experiences spiritual pain about.../" |\
sed -e "s/\\* lo ro nu jamna gi ga je/* all events (of war),/" |\
sed -e "s/\\* tu'a zo'e je lo vlile metfo gi ga je/* all events (of war),/" |\
sed -e "s/\\* lo ro nu jdini bilma gi ga je/* all events (of that some prenu experiences affluenza),/" |\
sed -e "s/\\* tu'a lo xarci gi ga je/* weapons,/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu pinfu gi ga je/\\* all events (of that some prenu is imprisoned),/" |\
sed -e "s/\\* lo ro vlile gi ga je/\\* all events (of violence),/" |\
sed -e "s/\\* lo ro nu ciztyolnei lo su'o prenu gi ga je/\\* all events (of xenophobia),/" |\
sed -e "s/\\* lo ro nu terpa tu'a lo tonsi je prenu gi ga je/\\* all events (of transphobia),/" |\
sed -e "s/\\* lo ro nu co'e ja xebni ja fengu lo su'o prenu kei noi ke'a nu xlafri jenai cu jimpe kei je cu filri'a lo nu zenba lo ka ce'u xi re xlafri gi ga je/\\* all events (of that some prenu $p$ exists such that some prenu is angry at $p$ or hates $p$) (which are events of that (prenu suffer and do not understand) and facilitate that prenu increase in suffering),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u su'o de poi ke'a prenu zo'u cfari fa lo nu da de skuxai ja ckasu poi ke'a xrani de ja cu nu da na co'e ja troci lo nu xajmi de gi ga je/\\* all events (of that some prenu $p$ exists such that some prenu $r$ exists such that $p$ insults $r$, and the event of insulting offends $r$ or is not an event of that $p$ attempts that $r$ is amused),/" |\
sed -e "s/\\* lo ro nu malku'i lo su'o prenu gi ga je/\\* all events (of that some prenu is mistreated),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka co'e ja troci lo nu jitro ce'u xi re tu'a lo lijda kei kei lo ka ce'u xi re terpa lo nu ri sezbanzu lo su'u ri co'e ja re'enje jurpei kei kei ja lo nu lo prenu jenai du be ce'u xi re cu seljda lo na lijda be ce'u xi re kei ja cu co'e ja jinvi lo du'u lo ro prenu cu seljda naja cu co'e ja troci lo nu ri jitro lo prenu jenai du be ri tu'a lo lijda gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ fears that ($p$ is independent in spiritually/whatever-ly considering stuff) or that (some prenu which is not $p$ "follows" a religion which is not "followed" by $p$) or opines/whatever that (for all prenu $r$, if $r$ is religious, then $r$ attempts "religiously" controlling/manipulating prenu which are not $r$)) in that prenu attempt/whatever to "religiously" control/manipulate $p$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu terpa lo nu ri co'e ja re'enje jurpei gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ fears that $p$ spiritually/whatever-ly considers stuff),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re terpa lo nu ri krici jenai djuno noi ke'a sarcu lo nu lijda ce'u xi re kei kei lo ka ce'u xi re co'e ja troci lo nu tolna'e tu'a lo lijda be ri kei kei noi ke'a jai filri'a ja rinka lo nu zenba lo ka ce'u xi re xlafri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that attempts/whatever that evidence indicates the religion/whatever of $p$) in fearing that ($p$ believes and does not know) (which is necessary for being religious)),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu terpa lo nu ri krici jenai djuno gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ fears that $p$ believes and does not know),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u da co'e ja jinvi lo du'u mabla ja tolvu'e fa lo ro da'i nu da seljda lo su'o co'e poi da na djuno lo du'u ke'a lijda lo su'o prenu jenai du be da gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ opines/whatever that all hypothetical events of that (some religion $r$ exists such that $p$ "follows" $r$, and no prenu which is not $p$ "follows" $r$) are fucked or immoral),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu co'e ja jinvi lo du'u sarcu fa lo nu ri seljda pe'a lo su'o na te krici be fi ri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ opines/whatever that a thing which is necessary is that $p$ "follows" a religion/whatever which is not believed by $p$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu terpa tu'a lo nu ri sanji lo co'e ja te toltu'i be fi ri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ fears that ($p$ is aware of things $s$ such that $p$ disagrees with/about $s$)),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu terpa tu'a lo co'e ja lijda be ri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ fears the religion/whatever of $p$),/" |\
sed -e "s/\\* lo si'o pacraistu gi ga je/\\* the idea (of hell),/" |\
sed -e "s/\\* lo ro nu lijda pe'a ke xlafri bilma gi ga je/\\* all events (of that some prenu experiences "religious" trauma),/" |\
sed -e "s/\\* lo ro nu su'o da zo'u lo su'o prenu cu co'e ja xusra lo du'u ri tugni fi da kei jenai ku'i cu jimpe fi da gi ga je/\\* all events (of that some thing $z exists such that some prenu $p$ exists such that $p$ asserts/whatever that ($p$ agrees with/about $z$)... but does not understand about $z$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka zo'e je lo ka ce'u xi re terpa lo nu ri to'e banzuka kei kei lo ka ce'u xi re co'e ja troci lo nu ri simlu lo ka ce'u xi ci banzuka kei kei joi lo nu lo prenu jenai du be ce'u xi re cu simlu lo ka ce'u xi ci to'e banzuka gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that ($p$ attempts/whatever that $p$ seems to be sufficient, and prenu which are not $p$ seem to be insufficient)) in fearing that $p$ is insufficient),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka zo'e je lo ka ce'u xi re terpa lo nu ri to'e banzuka kei kei lo ka ce'u xi re co'e ja troci lo nu ri smimlu lo prenu jenai du be ri kei jenai cu tarti tu'a ce'u xi re gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ attempts/whatever that ($p$ resembles prenu which are not $p$) and is not authentic to $p$) in fearing that $p$ is insufficient),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u su'o de poi ke'a jinzi da zo'u ga ja da terpa tu'a lo nu da tarti tu'a da ja cu stace fi tu'a da ja cu ckaji de gi lo su'o prenu noi da mupli tu'a ke'a cu co'e ja troci lo nu da na ckaji de gi ga je/\\* all events (of that some prenu $p$ exists such that some quality (which is inherent to $p$) $z$ exists such that ($p$ fears that ($p$ is authentic to $p$, is honest about $p$, or exhibits $z$), or some prenu, e.g., $p$, attempts/whatever that $p$ does not exhibit $z$)),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u lo su'o prenu noi da mupli tu'a ke'a cu banzuka lo ka ce'u xi re jundi lo se ckaji be da be'o ja lo bridi be fi da ce ce'u xi re be'o ja lo se zukte be da be'o noi mupli tu'a ke'a fa lo mabla ja tolvu'e je lo xajmi ja selnei be ce'u xi re kei lo ka ce'u xi re co'e ja tolmo'i lo du'u da prenu gi ga je/\\* all events (of that some prenu $p$ exists such that some prenu, e.g., $p$, $r$ exists such that $r$ is sufficient (for that $r$ forgets/whatever that $r$ is a prenu) in attending (to the relationship between $r$ and $p$) or in attending to the stuff (which is enacted by $p$) (which is exemplified by stuff (which amuses $p$), stuff which is liked by $p$, and stuff which is fucked or immoral)),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a zilkai je cu mabla ja tolvu'e zo'u lo su'o prenu cu banzuka zo'e je lo ka ce'u xi re terpa lo nu ri ckaji da kei kei lo ka ce'u xi re co'e ja troci lo nu na facki lo du'u xu kau ri ckaji da kei kei kei noi ke'a jai filri'a ja rinka lo nu zenba lo ka ce'u xi re xlafri kei kei je cu to'e jai filri'a lo nu jdika da gi ga je/\\* all events (of that some quality (which is fucked or immoral) (which is inherent to no prenu) $z$ exists such that some prenu $p$ exists such that $p$ is sufficient (for that ($p$ attempts/whatever that (prenu do not (regardless of whether $p$ exhibits $z$) determine whether $p$ exhibits $z$)) (which causes/facilitates increasing (in suffering) and anti-facilitates decreasing in $z$)) in fearing that $p$ exhibits $z$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re co'e ja troci lo nu nelci tu'a ri ja cu ci'au .uau tu'a lo se zukte be ce'u xi re kei kei lo ka ce'u xi re co'e ja tolmo'i lo du'u ri mo kau gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ forgets about the nature/identity/self/whatever of $p$) in attempting/whatever that prenu like $p$ or are impressed/amazed by the stuff which is done by $p$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu na tarti tu'a ri kei noi ke'a nu xlafri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is not authentic to $p$) (which are events of suffering),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu co'e ja jinvi lo du'u ri se xebni ja cu se prami lo no prenu gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ opines/whatever that ($p$ is hated) or that no prenu loves $p$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu troci lo nu ri jerna lo nu prami ri kei kei kei noi ke'a nu na jimpe fi py ky gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ attempts that $p$ earns being loved) (which are events of that some prenu does not understand),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu na'e jimpe lo du'u prami ri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ not-understands that $p$ is loved),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u co'e ja nandu fa lo nu ciksi fi da fe lo du'u prami da gi ga je/\\* all events (of that some prenu $p$ exists such that explaining (for $p$) that $p$ is loved is difficult or whatever),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re xenru kei lo ka ce'u xi re co'e ja tolmo'i lo du'u ri kakne lo zabna je vrude... je cu prenu gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ forgets that ($p$ is capable of stuff which rocks and is virtuous)... or that $p$ is a prenu, rocks, and is not an aggregate/whatever of the stuff which is enacted by $p$) in experiencing guilt),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u su'o de zo'u lo su'o prenu noi da mupli tu'a ke'a cu djuno lo du'u da de zukte je lo du'u de mabla ja tolvu'e kei je cu banzuka lo ka ce'u xi re terpa tu'a de lu'u ja tu'a da kei lo ka ce'u xi re co'e ja terpa ja toldji lo nu prami ja cnikansa da gi ga je/\\* all events (of that some prenu $p$ exists such that some thing $z$ exists such that some prenu $r$ exists such that $r$ knows that ($p$ enacts $z$) and that ($z$ is fucked or immoral) and is sufficient (for that $r$ fears/anti-desires/whatever some event of that prenu love $p$ or empathise with $p$) in fearing $z$ or $p$),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u lo su'o prenu noi da mupli tu'a ke'a cu co'e ja terpa ja toldji lo nu prami ja cnikansa da gi ga je/\\* all events (of that some prenu $p$ exists such that some prenu fears/anti-desires/whatever some event of that prenu love $p$ or empathise with $p$),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u lo su'o prenu noi da mupli tu'a ke'a cu co'e ja se nandu lo nu ri fraxu da gi ga je/\\* all events (of that some prenu $p$ exists such that forgiving $p$ is difficult/whatever for some prenu, e.g., $p$),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu terpa tu'a ri gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ fears $p$),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u su'o de poi ke'a prenu zo'u lo su'o prenu noi da je de mupli tu'a ke'a cu co'e ja jinvi lo du'u da zmadu de zo'e ja lo ka ce'u xi re co'e ja .inda lo ka prami ce'u xi ci gi ga je/\\* all events (of that some prenu $p$ exists such that some prenu $r$ exists such that some prenu, e.g., $p$ or $r$, opines/whatever that $p$ exceeds (in deserving living or in whatever) $r$),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u lo su'o prenu cu co'e ja djica lo su'o nu sfasa lo su'o prenu kei kei noi ke'a nu na jimpe gi ga je/\\* all events (of that some prenu $p$ exists such that some prenu desires/whatever that $p$ is punished) (which are events of that some prenu does not understand),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u lo su'o prenu cu co'e ja djica lo su'o nu jamna kei kei noi ke'a nu na jimpe fi lo nu jamna gi ga je/\\* all events (of that some prenu desires/whatever some event of war) (which are events of that some prenu does not understand),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu na'e jimpe le du'u no da poi ke'a prenu zo'u no de zo'u a zukte de ca lo nu da jimpe lo du'u de tolvu'e gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ not-understands that (no prenu $p$ exists such that some thing $z$ exists such that that ($p$ enacts $z$) happens and is contemporaneous with that $p$ understands that $z$ is immoral)),/" |\
sed -e "s/\\* lo nu co'e ja troci lo nu facki lo du'u xu kau lo mabla je tolvu'e cu zmadu lo mabla je tolvu'e le ka ce'u xi re mabla je tolvu'e gi ga je/\\* events (of that some prenu attempts determining whether a thing which is fucked and immoral exceeds (in being fucked and immoral) a thing which is fucked and immoral),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u lo su'o prenu cu co'e ja jinvi lo du'u sarcu fa lo su'o nu da xlafri ja lo su'o xrani be da gi ga je/\\* all events (of that some prenu opines/whatever that (some prenu $p$ exists such that a thing which is necessary is that ($p$ suffers) or that $p$ is harmed)),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu co'e ja jinvi lo du'u sarcu fa lo su'o mabla ja tolvu'e gi ga je/\\* all events (of that some prenu opines/whatever that some thing which is fucked or immoral is necessary),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re terpa tu'a lo prenu kei tu'a lo flalu gi ga je/\\* all events (of that some prenu is sufficient (for law stuff) in fearing prenu),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu co'e ja jinvi lo du'u lo flalu cu jai sarcu lo nu zifre gi ga je/\\* all events (of that some prenu opines/whatever that laws are necessary for being free),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re terpa kei lo ka ce'u xi re banzuka lo ka ce'u xi ci sutra kei lo ka ce'u xi ci srera se ri'a lo mabla ja tolvu'e noi mupli tu'a ke'a fa lo mrori'a be lo prenu gi ga je /\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ is sufficient (for that $p$ errs and accidentally enacts some thing which is fucked or immoral) in being fast) in experiencing fear),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka zo'e je lo ka ce'u xi re pensi lo purci ja lo balvi kei lo ka ce'u xi re co'e ja tolmo'i lo du'u ri zukte gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ forgets/whatever that $p$ is agentive) in thinking about the future or the past),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu co'e ja jinvi lo du'u ri na zifre gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ opines/whatever that $p$ is not free),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka zo'e je lo ka ce'u xi re terpa lo nu malku'i ri kei kei lo ka ce'u xi re malku'i lo prenu kei ja cu co'e ja troci lo nu na jimpe fi ce'u xi re gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ mistreats prenu or attempts/whatever that prenu do not understand about $p$) in fearing that $p$ is mistreated),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka malku'i ce'u xi re kei lo ka ce'u xi re co'e ja tolmo'i lo du'u na sarcu fa lo nu ri malku'i lo su'o prenu gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ forgets/whatever that that ($p$ mistreats prenu) is not necessary) in being mistreated),/" |\
sed -e "s/\\* lo ro nu xlafri bilma gi ga je/\\* all events (of that some prenu experiences trauma),/" |\
sed -e "s/\\* lo ro nu ci'au .a'o nai gi ga je/\\* all events (of that some prenu experiences despair),/" |\
sed -e "s/\\* le su'u lo so'i nu xamsku cu nu skuxai jenai cu co'e gi ga je/\\* that (many events of joking are events of that (prenu insult and-not do whatnot)),/" |\
sed -e "s/\\* le su'u lo xrani be lo prenu cu frili fi lo nu na jundi zo'e je lo prenu gi ga je/\\* that (accidentally enacting stuff which harms prenu is easy (under that prenu do not attend to prenu and whatnot)),/" |\
sed -e "s/\\* le su'u lo vlile cu jai filri'a lo nu terpa fa lo prenu jenai jimpe be fi py ky kei noi ke'a filri'a lo nu fengu noi ke'a xi re filri'a lo nu xebni noi ke'a xi re filri'a lo vlile gi ga je/\\* that (violence facilitates that (prenu which do not understand about the property of loving all prenu experience {VERB} fear), which facilitates that (prenu experience anger), which facilitates that (prenu hate), which facilitates violence),/" |\
sed -e "s/\\* le su'u lo jivna cemci'e cu jai filri'a lo mabla ja tolvu'e noi mupli tu'a ke'a fa lo ka ce'u xi re tolmo'i pe'a fi py ky gi ga je/\\* that (competitive society facilitates stuff (which is fucked or immoral) (which is exemplified by events of that "forget" about the property of loving all prenu)),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka tu'a lo bangu lu'u ja lo ka ce'u xi re besna pensi ja lo ka ce'u xi re mo'icli ja lo ka ce'u xi re troci lo nu ri djuno kei kei lo ka ce'u xi re na jimpe gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ does not understand) in language stuff, in memorising, in brain-thinking, in memorising, or in attempting that $p$ knows),/" |\
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u da troci lo nu da co'e ja gleki kei se ri'a lo nu da zenba lo ka ce'u xi re xlafri gi ga je/\\* all events (of that some prenu $p$ exists such that ($p$ attempts/whatever that ($p$ is happy/whatever), and the result is that $p$ increases in suffering)),/" |\
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re terpa tu'a lo nu ri co'e ja badri kei kei lo ka ce'u xi re co'e ja troci lo nu ri co'e ja fengu gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficent (for that $p$ attempts/whatever that $p$ is angry or whatever) in fearing that $p$ is sad or whatever),/"
sed -e "s/\\* lo ro nu lo su'o prenu cu co'e ja troci lo nu ri na co'e ja re'enje cinmo gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ attempts/whatever that $p$ does not feel),/"
sed -e "s/\\* lo ro nu lo su'o prenu cu terpa lo nu ri co'e ja re'enje cinmo gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ fears/whatever that $p$ feels),/"
sed -e "s/\\* lo ro nu su'o da poi ke'a prenu zo'u su'o de poi ke'a cmima ga ce lo ka ce'u xi re nu da ckaji py ky gi ga ce lo ka ce'u xi re nu da sisti lo pu'u da zukte lo mabla ja tolvu'e gi lo ka ce'u xi re nu da prane py ky zo'u da banzuka lo ka ce'u xi re terpa lo nu lo ckaji be de na cfari ja lo nu da fliba tu'a de kei kei lo ka ce'u xi re na curmi lo ckaji be de gi ga je/\\* all events (of that some prenu $p$ exists such that some element (of the set of that ($p$ exhibits the property of loving all prenu), that ($p$ stops enacting stuff which is fucked or immoral), and that $p$ is perfect/maximal in the property of loving all prenu) $x$ exists such that $p$ is sufficient (for that $p$ does not permit $x$) in fearing that ($x$ does not happen) or that $p$ fails to enact $x$),/"
sed -e "s/\\* lo ro nu lo su'o prenu cu banzuka lo ka ce'u xi re troci lo nu ri ckaji py ky kei kei lo ka ce'u xi re na ckaji py ky gi ga je/\\* all events (of that some prenu $p$ exists such that $p$ is sufficient (for that $p$ does not exhibit the property of loving all prenu) in attempting that $p$ exhibits the property of loving all prenu),/"
sed -e "s/\\* lo ro nu xlafri gi ga je/\\* all events (of that some prenu suffers),/"
sed -e "s/\\* lo ro nu ce'u co'e ja se jai fanza tu'a lo su'o prenu gi/\\* all events (of that VARIK is annoyed/whatever by some prenu),/"
sed -e "s/\\* lo ro nu ce'u na prane py ky kei noi ce'u fraxu ce'u ke'a gi ga ce/\\* all events (of that (VARIK is not perfect/maximal in the property of loving all prenu)) (which are forgiven by VARIK), and/"
sed -e "s/\\* le su'u cumki fa lo nu randa je lo nu cnikansa lo ro prenu zo'e je lo ka ce'u xi re xlafri kei kei je lo nu morji fi lo mabla ja tolvu'e je fasnu kei je lo nu prane py ky gi ga je/\\* that (yielding, empathising (in suffering and whatnot) (with all prenu), remembering about events which are fucked or immoral, and being perfect/maximal in the property of loving all prenu are possible),/"
